// FaultLog.cpp
//
// Compile this file into your application project (same as Factory.cpp etc.).
// It provides:
//   • The .noinit persistent fault record
//   • C++ API (FaultLogInit, FaultLogHasRecord, etc.)
//   • Cortex-M4 fault handler implementations (override the weak defaults)
//   • IWDG watchdog kick helper

extern "C" {
#include "stm32wlxx_hal.h"   // HAL_GetTick, RCC, IWDG
#include "iwdg.h"            // hiwdg — generated by CubeMX; add IWDG to your .ioc
}

#include "FaultLog.hpp"
#include <cstring>
#include <cstdio>

namespace Diag {

// ---------------------------------------------------------------------------
// Persistent storage — .noinit means startup code does NOT zero this.
// After a watchdog reset or fault the previous contents survive intact.
// ---------------------------------------------------------------------------
__attribute__((section(".noinit")))
FaultRecord g_fault_log;

// ---------------------------------------------------------------------------
// FaultLogInit — call at the very top of main(), before HAL_Init()
// ---------------------------------------------------------------------------
void FaultLogInit() {
    // Snapshot reset cause BEFORE HAL_Init() clears RCC_CSR.
    const uint32_t csr = RCC->CSR;
    RCC->CSR |= RCC_CSR_RMVF;   // clear reset flags for next boot

    if (g_fault_log.magic == FaultRecord::kMagic) {
        // Valid record from a previous fault / watchdog expiry.
        // Preserve it; just update the reset-cause snapshot and increment boot count.
        g_fault_log.rcc_csr = csr;
        g_fault_log.boot_count++;
        // A watchdog (IWDG) reset leaves no fault-handler record — the hardware
        // resets the CPU with nothing running.  If this boot followed an IWDG
        // reset and no handler already tagged the record (a HardFault/assert
        // resets via its own path and sets fault_type first), classify it as a
        // hang so the last checkpoint tag + uptime that KickWatchdog() wrote
        // before the stall are reported (NFR-10 / issue #17).
        if ((csr & RCC_CSR_IWDGRSTF) && g_fault_log.fault_type == FaultType::None) {
            g_fault_log.fault_type = FaultType::WatchdogHang;
        }
    } else {
        // First power-on or corrupted record — initialise cleanly.
        std::memset(&g_fault_log, 0, sizeof(g_fault_log));
        g_fault_log.magic      = FaultRecord::kMagic;
        g_fault_log.fault_type = FaultType::None;
        g_fault_log.rcc_csr    = csr;
        g_fault_log.boot_count = 1;
    }
}

bool FaultLogHasRecord() {
    return (g_fault_log.magic == FaultRecord::kMagic) &&
           (g_fault_log.fault_type != FaultType::None);
}

const FaultRecord* FaultLogGet() {
    return &g_fault_log;
}

void FaultLogClear() {
    g_fault_log.fault_type = FaultType::None;
    std::memset(&g_fault_log.frame, 0, sizeof(g_fault_log.frame));
    g_fault_log.watchdog_checkpoint = 0;
    g_fault_log.uptime_ms = 0;
    std::memset(g_fault_log.assert_file, 0, sizeof(g_fault_log.assert_file));
    g_fault_log.assert_line = 0;
    // magic and boot_count are intentionally preserved
}

void KickWatchdog(uint32_t checkpoint_tag) {
    g_fault_log.watchdog_checkpoint = checkpoint_tag;
    g_fault_log.uptime_ms = HAL_GetTick();
    HAL_IWDG_Refresh(&hiwdg);
}

void FaultAssert(const char* file, uint32_t line) {
    g_fault_log.fault_type  = FaultType::AssertFail;
    g_fault_log.uptime_ms   = HAL_GetTick();
    g_fault_log.assert_line = line;
    std::strncpy(g_fault_log.assert_file, file, sizeof(g_fault_log.assert_file) - 1);
    // Trigger a deliberate HardFault to capture the full CPU state.
    // The HardFault handler will fill in the ExceptionFrame.
    __BKPT(0);          // if debugger attached it stops here; otherwise falls to HardFault
    *reinterpret_cast<volatile uint32_t*>(0xE000ED04) = (1u << 31); // force NMI (safe trigger)
}

} // namespace Diag

// ---------------------------------------------------------------------------
// Fault handler core — called by each assembly trampoline below.
// sp_frame points to the automatically-saved Cortex-M4 exception stack frame.
// fault_type identifies which vector fired.
// ---------------------------------------------------------------------------
// extern "C" gives this function a plain unmangled name so the naked assembly
// handlers can reach it with a simple 'b SaveFaultAndHalt' branch instruction.
// Removing 'static' gives it external linkage for the same reason.
extern "C" void SaveFaultAndHalt(uint32_t* sp_frame, uint32_t fault_type) {
    // Cast the raw uint32_t back to the enum for storage
    Diag::g_fault_log.fault_type = static_cast<Diag::FaultType>(fault_type);
    Diag::g_fault_log.uptime_ms  = HAL_GetTick();

    // Copy the CPU-pushed exception frame
    Diag::g_fault_log.frame.r0   = sp_frame[0];
    Diag::g_fault_log.frame.r1   = sp_frame[1];
    Diag::g_fault_log.frame.r2   = sp_frame[2];
    Diag::g_fault_log.frame.r3   = sp_frame[3];
    Diag::g_fault_log.frame.r12  = sp_frame[4];
    Diag::g_fault_log.frame.lr   = sp_frame[5];
    Diag::g_fault_log.frame.pc   = sp_frame[6];   // ← faulting instruction
    Diag::g_fault_log.frame.xpsr = sp_frame[7];

    // Stack pointer (useful to spot overflow against _estack symbol)
    Diag::g_fault_log.sp = reinterpret_cast<uint32_t>(sp_frame);

    // ARM fault status registers
    Diag::g_fault_log.cfsr  = SCB->CFSR;
    Diag::g_fault_log.hfsr  = SCB->HFSR;
    Diag::g_fault_log.mmfar = SCB->MMFAR;
    Diag::g_fault_log.bfar  = SCB->BFAR;

    // Clear fault status so they're valid on the next read
    SCB->CFSR  = SCB->CFSR;
    SCB->HFSR  = SCB->HFSR;

    // Brief LED indicator — assumes RgbLed is safe to call (GPIOs stay clocked
    // through a reset; the GPIO peripheral is not affected by a CPU fault).
    // If your RgbLed function touches anything unsafe, comment this out.
    // RgbLed(RgbColor::Red);

    // Reset after a short delay so the watchdog behaviour is consistent
    // (the IWDG will reset us anyway, but an explicit reset is cleaner).
    HAL_Delay(200);
    NVIC_SystemReset();
}

// ---------------------------------------------------------------------------
// Cortex-M4 assembly trampolines
//
// The processor pushes {R0-R3, R12, LR, PC, xPSR} onto either MSP or PSP
// before entering the vector.  We determine which, then call the C handler.
//
// These REPLACE the weak default handlers defined in startup_stm32wlxx.s.
// If your startup file already defines (non-weak) handlers you will get a
// linker conflict — comment out the conflicting ones in the startup file.
// ---------------------------------------------------------------------------
extern "C" {

__attribute__((naked)) void HardFault_Handler(void) {
    __asm volatile (
        "tst    lr, #4              \n"
        "ite    eq                  \n"
        "mrseq  r0, msp             \n"
        "mrsne  r0, psp             \n"
        "ldr    r1, =0xFA01FA01     \n"  // FaultType::HardFault
        "b      SaveFaultAndHalt    \n"
    );
}

__attribute__((naked)) void BusFault_Handler(void) {
    __asm volatile (
        "tst    lr, #4              \n"
        "ite    eq                  \n"
        "mrseq  r0, msp             \n"
        "mrsne  r0, psp             \n"
        "ldr    r1, =0xFA02FA02     \n"  // FaultType::BusFault
        "b      SaveFaultAndHalt    \n"
    );
}

__attribute__((naked)) void UsageFault_Handler(void) {
    __asm volatile (
        "tst    lr, #4              \n"
        "ite    eq                  \n"
        "mrseq  r0, msp             \n"
        "mrsne  r0, psp             \n"
        "ldr    r1, =0xFA03FA03     \n"  // FaultType::UsageFault
        "b      SaveFaultAndHalt    \n"
    );
}

__attribute__((naked)) void MemManage_Handler(void) {
    __asm volatile (
        "tst    lr, #4              \n"
        "ite    eq                  \n"
        "mrseq  r0, msp             \n"
        "mrsne  r0, psp             \n"
        "ldr    r1, =0xFA04FA04     \n"  // FaultType::MemManage
        "b      SaveFaultAndHalt    \n"
    );
}

} // extern "C"

// ---------------------------------------------------------------------------
// C-linkage wrappers — called from main.c via FaultLogC.h
// (previously in FaultLog_c_wrappers.cpp — consolidated here)
// ---------------------------------------------------------------------------
extern "C" {

void FaultLog_Init(void) {
    Diag::FaultLogInit();
}

void FaultLog_KickWatchdog(unsigned int checkpoint_tag) {
    Diag::KickWatchdog(static_cast<uint32_t>(checkpoint_tag));
}

} // extern "C"
